insert into operation_hours
VALUES
((SELECT id FROM breweries WHERE name = 'Dos Luces Brewery'),2,'16:00','22:00'),
((SELECT id FROM breweries WHERE name = 'Dos Luces Brewery'),3,'16:00','22:00'),
((SELECT id FROM breweries WHERE name = 'Dos Luces Brewery'),4,'16:00','22:00'),
((SELECT id FROM breweries WHERE name = 'Dos Luces Brewery'),5,'13:00','22:00'),
((SELECT id FROM breweries WHERE name = 'Dos Luces Brewery'),6,'12:00','22:00'),
((SELECT id FROM breweries WHERE name = 'Dos Luces Brewery'),7,'12:00','21:00'),
((SELECT id FROM breweries WHERE name = 'Great Divide Brewing Company'),1,'15:00','21:00'),
((SELECT id FROM breweries WHERE name = 'Great Divide Brewing Company'),2,'15:00','21:00'),
((SELECT id FROM breweries WHERE name = 'Great Divide Brewing Company'),3,'15:00','21:00'),
((SELECT id FROM breweries WHERE name = 'Great Divide Brewing Company'),4,'15:00','21:00'),
((SELECT id FROM breweries WHERE name = 'Great Divide Brewing Company'),5,'15:00','21:00'),
((SELECT id FROM breweries WHERE name = 'Great Divide Brewing Company'),6,'15:00','21:00'),
((SELECT id FROM breweries WHERE name = 'Great Divide Brewing Company'),7,'15:00','21:00'),
((SELECT id FROM breweries WHERE name = 'San Luis Valley Brewing Company'),1,'11:00','21:00'),
((SELECT id FROM breweries WHERE name = 'San Luis Valley Brewing Company'),2,'11:00','21:00'),
((SELECT id FROM breweries WHERE name = 'San Luis Valley Brewing Company'),3,'11:00','21:00'),
((SELECT id FROM breweries WHERE name = 'San Luis Valley Brewing Company'),4,'11:00','21:00'),
((SELECT id FROM breweries WHERE name = 'San Luis Valley Brewing Company'),5,'11:00','22:00'),
((SELECT id FROM breweries WHERE name = 'San Luis Valley Brewing Company'),6,'11:00','22:00'),
((SELECT id FROM breweries WHERE name = 'San Luis Valley Brewing Company'),7,'11:00','21:00'),
((SELECT id FROM breweries WHERE name = 'Epic Brewing Company, LLC'),1,'11:00','21:00'),
((SELECT id FROM breweries WHERE name = 'Epic Brewing Company, LLC'),2,'11:00','21:00'),
((SELECT id FROM breweries WHERE name = 'Epic Brewing Company, LLC'),3,'11:00','21:00'),
((SELECT id FROM breweries WHERE name = 'Epic Brewing Company, LLC'),4,'11:00','21:00'),
((SELECT id FROM breweries WHERE name = 'Epic Brewing Company, LLC'),5,'10:00','23:00'),
((SELECT id FROM breweries WHERE name = 'Epic Brewing Company, LLC'),6,'10:00','23:00'),
((SELECT id FROM breweries WHERE name = 'Epic Brewing Company, LLC'),7,'11:00','19:00'),
((SELECT id FROM breweries WHERE name = 'Prost Brewing'),1,'12:00','22:00'),
((SELECT id FROM breweries WHERE name = 'Prost Brewing'),2,'12:00','22:00'),
((SELECT id FROM breweries WHERE name = 'Prost Brewing'),3,'12:00','22:00'),
((SELECT id FROM breweries WHERE name = 'Prost Brewing'),4,'12:00','22:00'),
((SELECT id FROM breweries WHERE name = 'Prost Brewing'),5,'12:00','22:00'),
((SELECT id FROM breweries WHERE name = 'Prost Brewing'),6,'12:00','22:00'),
((SELECT id FROM breweries WHERE name = 'Prost Brewing'),7,'12:00','20:00');

select breweries.name,beers.name from beers join breweries on breweries.id=beers.brewery_id
 where beers.name not null